"""T-94 — the third practice's charts, as committed (US-10, D114).

`tests/test_ultrasound_tree.py` asks whether the tree loads, resolves and
evaluates, over charts written in that file. This file asks the other half,
in `test_rheumatology_corpus.py`'s shape: do the **committed bundles** carry
what the eval rows say they carry, and does a determination over them answer
what the rows label?

What it pins:

- **The cohort.** Three charts: one generated by Synthea in WPS's territory
  and two declared clones of it, each carrying one prior study copied from a
  procedure the patient already had and re-coded. The pair differs by exactly
  the date that decides the frequency criterion.
- **Membership, not codes.** `select_patients.py` selects on codes read out of
  the Synthea modules; this is where those codes are asserted to be what the
  policy plane's value sets admit, in each set's declared system (REQ-59). A
  test comparing codes to codes would pass with the value sets deleted.
- **The verdicts.** Each row's labeled criteria over the real store, with an
  extraction runner that raises: this tree declares no note criterion, so zero
  model calls is a property of the graph and not of a counter.
- **The spans.** Every cited span slices back into the bundle it names, which
  is the whole of Article III on the structured plane.

**What this file cannot catch, and where that claim lives.** No committed
chart carries an abdominal vascular study at an emergency or inpatient
encounter, or one the record disowns — the declared studies are copies of
ambulatory, completed procedures — so a predicate that ignored L35755's
care-setting carve-out, or counted a `not-done` study, would pass everything
here. Both are caught by `test_ultrasound_tree.py` on charts written in the
test (D65's division, D113's tenth mutation seen coming).
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import pytest

from pa_agent.contracts import CriterionVerdict, DeterminationOutcome, GapReason
from pa_agent.determination import determine
from pa_agent.stores.patient import LocalPatientStore
from pa_agent.stores.policy import LocalPolicyStore

from conftest import AcceptAllVerifier

REPO_ROOT = Path(__file__).resolve().parent.parent
POPULATION = REPO_ROOT / "data" / "patients" / "manifest.json"
BUNDLES = REPO_ROOT / "data" / "patients" / "bundles"
CASES = REPO_ROOT / "eval" / "cases.json"

TREE_ID = "us-abdominal-visceral-j5-j8-v1"
US_CODE = "93975"
UNLISTED_CODE = "76700"
WPS_STATE_CODE = "IA"

SNOMED = "http://snomed.info/sct"
STUDY = "709640007"
INDICATIONS = "abdominal_visceral_vascular_indications"
STUDIES = "abdominal_visceral_vascular_studies"

#: The three charts by the row each one carries. Written here rather than
#: derived, so a chart swapped underneath the eval set fails this file first.
BASE = "53126ee7-0f8a-b494-fb3c-921069a1605b"  # the generated chart, no study
US1 = "b1bbb34a-aa4b-5c18-a550-8bd26e0da528"  # one study, outside the interval
US2 = "7acd0453-b37c-5c1a-9879-0a7b443065d9"  # one study, inside it

#: `US2` pins its own `as_of` because the `NOT_MET` direction ages out; the
#: other two do not need one and are read at the harness clock (D114).
US2_AS_OF = date(2026, 9, 1)
AS_OF = date(2026, 9, 1)


class _RaisingRunner:
    name = "raising"

    def run(self, *args, **kwargs):  # pragma: no cover - the point is the raise
        raise AssertionError("the ultrasound tree declares no note criterion")


@pytest.fixture(scope="module")
def population() -> dict:
    return json.loads(POPULATION.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def patients() -> LocalPatientStore:
    return LocalPatientStore()


@pytest.fixture(scope="module")
def policies() -> LocalPolicyStore:
    return LocalPolicyStore()


@pytest.fixture(scope="module")
def cases() -> list[dict]:
    return json.loads(CASES.read_text(encoding="utf-8"))["cases"]


def _determine(patients, policies, patient_id, code=US_CODE, as_of=AS_OF):
    return determine(
        policies,
        code,
        patient_id=patient_id,
        patient_store=patients,
        as_of=as_of,
        extraction_runner=_RaisingRunner(),
        verifier=AcceptAllVerifier(),
    )


def _result(determination, criterion_id: str):
    return next(
        r for r in determination.criterion_results if r.criterion_id == criterion_id
    )


def _record(population: dict, patient_id: str) -> dict:
    return next(r for r in population["bundles"] if r["patient_id"] == patient_id)


# --------------------------------------------------------------------------
# The cohort
# --------------------------------------------------------------------------


def test_the_population_carries_three_ultrasound_charts(population):
    cohort = [r for r in population["bundles"] if r["cohort"] == "ultrasound"]
    assert sorted(r["patient_id"] for r in cohort) == sorted([BASE, US1, US2])


def test_the_generated_chart_carries_the_indication_and_no_study_of_its_own(
    population,
):
    record = _record(population, BASE)
    assert record["active_indication_codes"], "criterion (a)'s fact"
    assert record["prior_study_dates"] == [], (
        "the generated chart carries no abdominal vascular study, so each "
        "clone's declared study is the only one on its chart"
    )


def test_each_clone_carries_exactly_one_declared_study_and_the_dates_differ(
    population,
):
    outside = _record(population, US1)["prior_study_dates"]
    inside = _record(population, US2)["prior_study_dates"]
    assert len(outside) == len(inside) == 1
    assert outside[0][:10] == "2024-06-17"
    assert inside[0][:10] == "2026-05-25"


def test_the_pair_differs_by_exactly_the_declared_procedure(population):
    """`US1` and `US2` are the same chart with a different procedure copied
    and re-coded. Asserted on the bytes, because the whole legibility of the
    two rows is that one field moved (D113's shape for the prescription)."""
    entries = {}
    for patient_id in (US1, US2):
        bundle = json.loads(
            (BUNDLES / _record(population, patient_id)["filename"]).read_text(
                encoding="utf-8"
            )
        )
        entries[patient_id] = [
            e
            for e in bundle["entry"]
            if e["resource"]["resourceType"] == "Procedure"
            and STUDY in {c["code"] for c in e["resource"]["code"]["coding"]}
        ]
    for patient_id, declared in entries.items():
        assert len(declared) == 1, f"{patient_id} carries {len(declared)} declared study"
        assert declared[0]["resource"]["id"].endswith("-us-prior-synthetic")
    assert entries[US1][0]["resource"]["encounter"] != (
        entries[US2][0]["resource"]["encounter"]
    ), "the two studies were copied from procedures at different encounters"


def test_the_charts_are_in_a_state_the_ultrasound_tree_serves(patients, policies):
    for patient_id in (BASE, US1, US2):
        state = patients.get_jurisdiction_state(patient_id)
        assert state == WPS_STATE_CODE
        assert policies.resolve(US_CODE, state).policy_version_id == TREE_ID


# --------------------------------------------------------------------------
# Membership, in each set's declared system
# --------------------------------------------------------------------------


def test_the_chart_s_conditions_are_admitted_by_the_indication_set(
    patients, policies
):
    """The value set is the policy plane's claim about what those codes mean;
    the selector only compared codes to codes (Art. VI, REQ-59)."""
    value_set = policies.get_value_set(INDICATIONS)
    admitted = [
        c
        for c in patients.get_conditions(BASE)
        if c.clinical_status == "active" and value_set.admits(c.code, c.system)
    ]
    assert len(admitted) >= 1
    assert {c.system for c in admitted} == {value_set.system}


def test_the_declared_study_is_admitted_by_the_study_set(patients, policies):
    value_set = policies.get_value_set(STUDIES)
    for patient_id in (US1, US2):
        admitted = [
            p
            for p in patients.get_procedures(patient_id)
            if value_set.admits(p.code, p.system)
        ]
        assert len(admitted) == 1
        assert admitted[0].code == STUDY
        assert admitted[0].system == value_set.system
    assert not [
        p
        for p in patients.get_procedures(BASE)
        if value_set.admits(p.code, p.system)
    ]


def test_the_declared_studies_sit_outside_the_excluded_care_settings(patients):
    """The carve-out is the predicate's, and this is the fact that makes it
    inert over this corpus — which is why the behaviour itself is pinned in
    `test_ultrasound_tree.py` and recorded in D114 rather than assumed."""
    for patient_id in (US1, US2):
        declared = [p for p in patients.get_procedures(patient_id) if p.code == STUDY]
        assert [p.encounter_class for p in declared] == ["AMB"]
        assert [p.status for p in declared] == ["completed"]


def test_every_procedure_on_these_charts_resolves_its_care_setting(patients):
    """`Procedure.encounter_class` is `None` when the adapter cannot resolve
    the encounter, and an unresolved setting counts rather than being
    excluded. Measured here so a bundle that started carrying dangling
    encounter references would fail loudly instead of quietly widening what
    the frequency criterion counts (D114)."""
    for patient_id in (BASE, US1, US2):
        unresolved = [
            p for p in patients.get_procedures(patient_id) if p.encounter_class is None
        ]
        assert not unresolved, f"{patient_id}: {len(unresolved)} unresolved setting(s)"


# --------------------------------------------------------------------------
# The verdicts the rows label
# --------------------------------------------------------------------------


def test_us1_meets_both_claimed_criteria_and_abstains_on_the_rest(
    patients, policies
):
    determination = _determine(patients, policies, US1)
    assert determination.policy_version_id == TREE_ID
    assert determination.outcome is DeterminationOutcome.INSUFFICIENT_EVIDENCE
    assert _result(determination, "a").verdict is CriterionVerdict.MET
    interval = _result(determination, "b")
    assert interval.verdict is CriterionVerdict.MET
    assert len(interval.spans) == 1
    for criterion_id in ("c", "d", "e"):
        result = _result(determination, criterion_id)
        assert result.verdict is CriterionVerdict.INSUFFICIENT_EVIDENCE
        assert result.gap_reason is GapReason.NOT_EVALUATED_BY_THIS_SYSTEM


def test_us2_is_not_met_and_cites_the_study_inside_the_interval(patients, policies):
    determination = _determine(patients, policies, US2, as_of=US2_AS_OF)
    assert determination.outcome is DeterminationOutcome.NOT_MET
    interval = _result(determination, "b")
    assert interval.verdict is CriterionVerdict.NOT_MET
    assert interval.shortfall.observed == 3
    assert interval.shortfall.required == 12
    assert interval.shortfall.unit == "months_since_prior_procedure"
    assert len(interval.spans) == 1


def test_us2_cites_the_declared_study_and_not_some_other_procedure(
    patients, policies
):
    """A denial that cited the wrong resource would still be a denial, and
    every other check here would agree with it (D113's rule for the
    exclusion, on the criterion this row turns on)."""
    determination = _determine(patients, policies, US2, as_of=US2_AS_OF)
    cited = _result(determination, "b").spans[0]
    declared = next(
        p for p in patients.get_procedures(US2) if p.code == STUDY
    )
    assert cited == declared.span


def test_us3_abstains_on_the_frequency_criterion_and_never_answers_met(
    patients, policies
):
    determination = _determine(patients, policies, BASE)
    assert determination.outcome is DeterminationOutcome.INSUFFICIENT_EVIDENCE
    assert _result(determination, "a").verdict is CriterionVerdict.MET
    interval = _result(determination, "b")
    assert interval.verdict is CriterionVerdict.INSUFFICIENT_EVIDENCE
    assert interval.gap_reason is GapReason.NO_EVIDENCE_RETRIEVED
    assert interval.spans == []


def test_us4_is_no_policy_found_in_a_state_that_is_served(patients, policies):
    result = _determine(patients, policies, BASE, code=UNLISTED_CODE)
    assert type(result).__name__ == "NoPolicyResult"
    assert policies.trees_for_state(WPS_STATE_CODE)


def test_every_cited_span_slices_back_into_the_bundle_it_names(patients, policies):
    """Article III over the structured plane: the span is an extent in the
    bundle's own JSON, and slicing it has to reach the resource the verdict
    says it cites."""
    checked = 0
    for patient_id, as_of in ((US1, AS_OF), (US2, US2_AS_OF), (BASE, AS_OF)):
        determination = _determine(patients, policies, patient_id, as_of=as_of)
        for result in determination.criterion_results:
            for span in result.spans:
                document = patients.get_document(span.document_id)
                sliced = document.text[span.char_start : span.char_end]
                assert json.loads(sliced)["resourceType"] in {
                    "Condition",
                    "Procedure",
                }
                checked += 1
    assert checked >= 9


def test_every_ultrasound_determination_spends_no_model_call(patients, policies):
    for patient_id, as_of in ((US1, AS_OF), (US2, US2_AS_OF), (BASE, AS_OF)):
        determination = _determine(patients, policies, patient_id, as_of=as_of)
        assert not determination.metrics


def test_no_ultrasound_criterion_cites_a_note(patients, policies):
    """These charts are note-free, and the tree declares no note criterion.
    Pinned because `step_extract` is unconditional (D113's finding): a chart
    with notes under this tree would still be read, and the guarantee that
    matters is that nothing it read reaches a verdict. T-107 removes the
    call."""
    note_ids = {d.document_id for d in patients.get_notes(US1)}
    assert note_ids == set()
    determination = _determine(patients, policies, US1)
    cited = {s.document_id for r in determination.criterion_results for s in r.spans}
    assert not cited & note_ids


# --------------------------------------------------------------------------
# The rows and the cohort agree
# --------------------------------------------------------------------------


def test_every_ultrasound_row_names_a_chart_in_the_cohort(cases, population):
    cohort = {
        r["patient_id"] for r in population["bundles"] if r["cohort"] == "ultrasound"
    }
    rows = [c for c in cases if c["case_id"].startswith("US")]
    assert len(rows) == 4
    for row in rows:
        assert row["patient_id"] in cohort, row["case_id"]


def test_only_the_row_whose_verdict_ages_pins_an_as_of(cases):
    """The `MET` direction is monotone in time and the `NOT_MET` direction is
    not, so exactly one of these rows carries its own clock (D114)."""
    rows = {c["case_id"]: c for c in cases if c["case_id"].startswith("US")}
    assert rows["US2"]["as_of"] == US2_AS_OF.isoformat()
    for case_id in ("US1", "US3", "US4"):
        assert "as_of" not in rows[case_id]
