"""T-93 — the second practice's charts, as committed (US-10, D113).

`tests/test_infliximab_tree.py` asks whether the tree loads, resolves and
evaluates; it does that over charts written in the test, so it says nothing
about whether a real one exists. This file asks the other half: do the
**committed bundles** carry what the eval rows say they carry, and does a
determination over them answer what the rows label?

What it pins, in the order the question breaks down:

- **The cohort.** Three charts, two generated by Synthea in Palmetto GBA's
  territory and one a declared clone of the first. The generated pair differs
  on exactly the fact criterion (b) turns on.
- **Membership, not codes.** `select_patients.py` selects on codes read out of
  the Synthea module; this is where those codes are asserted to be what the
  policy plane's value sets admit, in each set's declared system (REQ-59).
  A test that only compared codes to codes would pass with the value sets
  deleted.
- **The verdicts.** Each row's labeled criteria, produced over the real store
  with an extraction runner that raises — the rheumatology tree declares no
  note criterion, so zero model calls is a property of the graph and not of a
  counter (A4's shape).
- **The pair.** `RA2` is `RA1`'s chart plus one prescription, and the denial
  cites that prescription. Both halves are asserted: a denial that cited
  something else would still be a denial, and every other test would agree
  with it.
- **What the adapter cannot see.** `get_medications` does not follow a
  `medicationReference` (D111's stated scope). These charts carry such orders;
  none of them is a drug any rheumatology criterion or exclusion reads. That
  was measured for D113 and is pinned here, because a corpus change that put
  methotrexate behind a reference would move an eval label with every other
  check green.

**What this file cannot catch, and where that claim lives.** No committed
chart carries a *completed* order for a drug in either value set — the two
generated charts have one active methotrexate order and none at all, and the
clone adds an active one — so deleting the `status == "active"` filter from
`_active_members` changes nothing here. It is caught by
`test_infliximab_tree.py`, whose charts are written in the test and can hold
a completed order (D65's shape: the corpus cannot distinguish what it does
not contain). Measured by mutation at T-93's close, not assumed.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import pytest

from pa_agent.contracts import CriterionVerdict, DeterminationOutcome, GapReason
from pa_agent.determination import determine
from pa_agent.runners import RecordedExtractionRunner
from pa_agent.stores.patient import LocalPatientStore
from pa_agent.stores.policy import LocalPolicyStore

from conftest import AcceptAllVerifier

REPO_ROOT = Path(__file__).resolve().parent.parent
POPULATION = REPO_ROOT / "data" / "patients" / "manifest.json"
CASES = REPO_ROOT / "eval" / "cases.json"

TREE_ID = "infliximab-ra-jjm-v1"
J_CODE = "J1745"
#: The harness clock (D35), which every row without its own `as_of` reads.
AS_OF = date(2026, 9, 1)

SNOMED = "http://snomed.info/sct"
RXNORM = "http://www.nlm.nih.gov/research/umls/rxnorm"
RA_SNOMED = "69896004"
METHOTREXATE_TABLET = "105585"
ETANERCEPT_SYRINGE = "802652"

#: The three charts by the row each one carries. Written here rather than
#: derived, so a chart swapped underneath the eval set fails this file first.
RA1 = "42a430ab-b7ca-87a5-279f-ee115f49fd6e"  # active diagnosis, active drug
RA2 = "915602a8-a36d-59bf-b667-47496ab57965"  # RA1 plus the excluded drug
RA3 = "455d3f7d-3b99-dad6-c0b2-d5405144e793"  # active diagnosis, no drug


class _RaisingRunner:
    """A4: reached only if the graph asks a model something. It must not."""

    name = "raises"

    def run(self, *args, **kwargs):  # pragma: no cover - the point is it is unused
        raise AssertionError(
            "the rheumatology tree declares no note-event criterion; extraction "
            "must never be reached"
        )


@pytest.fixture(scope="module")
def patients() -> LocalPatientStore:
    return LocalPatientStore()


@pytest.fixture(scope="module")
def policies() -> LocalPolicyStore:
    return LocalPolicyStore()


@pytest.fixture(scope="module")
def population() -> dict[str, dict]:
    manifest = json.loads(POPULATION.read_text(encoding="utf-8"))
    return {r["patient_id"]: r for r in manifest["bundles"]}


@pytest.fixture(scope="module")
def cases() -> dict[str, dict]:
    payload = json.loads(CASES.read_text(encoding="utf-8"))
    return {c["case_id"]: c for c in payload["cases"]}


def _determine(patients, policies, patient_id):
    return determine(
        policies,
        J_CODE,
        patient_id=patient_id,
        patient_store=patients,
        as_of=AS_OF,
        extraction_runner=_RaisingRunner(),
        verifier=AcceptAllVerifier(),
    )


def _recorded_runner():
    """T-15's recording, for the one case here whose chart carries notes.
    Spends nothing and replays what was measured (D45)."""
    recording = json.loads(
        (REPO_ROOT / "eval" / "extraction" / "results.json").read_text(encoding="utf-8")
    )
    return RecordedExtractionRunner.from_records(
        recording["notes"], model=recording.get("model")
    )


# --------------------------------------------------------------------------
# The cohort: what the population declares
# --------------------------------------------------------------------------


def test_the_population_carries_three_rheumatology_charts(population):
    cohort = {
        pid: r for pid, r in population.items() if r.get("cohort") == "rheumatology"
    }
    assert set(cohort) == {RA1, RA2, RA3}, (
        "the rheumatology cohort is the two generated charts and the declared "
        "clone of the first (D113)"
    )


def test_the_generated_pair_differs_on_the_drug_criterions_fact(population):
    """Both carry the diagnosis; one carries the drug. That is the whole
    difference the pair exists to make, and it is what lets criterion (a) hold
    fixed while criterion (b) moves."""
    assert population[RA1]["has_active_ra"] and population[RA3]["has_active_ra"]
    assert population[RA1]["has_active_methotrexate"]
    assert not population[RA3]["has_active_methotrexate"]
    assert population[RA3]["methotrexate_orders"] == 0, (
        "RA3's abstention is about a chart with no such order at all, not one "
        "whose order has ended — a completed order is a different case and "
        "test_infliximab_tree.py pins it"
    )


def test_only_the_declared_clone_carries_the_excluded_drug(population):
    carriers = [
        pid for pid, r in population.items() if r.get("has_active_excluded_biologic")
    ]
    assert carriers == [RA2], (
        "Synthea's rheumatoid arthritis module orders no biologic and no JAK "
        "inhibitor, so the only chart carrying one is the declared clone (D113)"
    )


def test_the_charts_are_in_a_state_the_rheumatology_tree_serves(patients, policies):
    tree = policies.get_tree(TREE_ID)
    for patient_id in (RA1, RA2, RA3):
        state = patients.get_jurisdiction_state(patient_id)
        assert state in tree.jurisdiction.states, (
            f"{patient_id[:12]} is in {state}, which this tree does not serve; "
            "the request would resolve elsewhere or not at all (REQ-55)"
        )


# --------------------------------------------------------------------------
# Membership: the codes the charts carry are the codes the value sets admit
# --------------------------------------------------------------------------


def test_the_diagnosis_is_admitted_by_the_value_set_in_its_declared_system(
    patients, policies
):
    value_set = policies.get_value_set("rheumatoid_arthritis")
    for patient_id in (RA1, RA3):
        conditions = [
            c
            for c in patients.get_conditions(patient_id)
            if c.clinical_status == "active" and value_set.admits(c.code, c.system)
        ]
        assert [c.code for c in conditions] == [RA_SNOMED]
        assert {c.system for c in conditions} == {SNOMED}, (
            "membership is tested inside the set's declared system (REQ-59)"
        )


def test_the_drug_sets_admit_exactly_what_each_chart_carries(patients, policies):
    methotrexate = policies.get_value_set("methotrexate")
    biologics = policies.get_value_set("biologic_dmards_and_jak_inhibitors")

    def admitted(patient_id, value_set):
        return sorted(
            m.code
            for m in patients.get_medications(patient_id)
            if m.status == "active" and value_set.admits(m.code, m.system)
        )

    assert admitted(RA1, methotrexate) == [METHOTREXATE_TABLET]
    assert admitted(RA1, biologics) == []
    assert admitted(RA3, methotrexate) == []
    assert admitted(RA3, biologics) == []
    assert admitted(RA2, methotrexate) == [METHOTREXATE_TABLET]
    assert admitted(RA2, biologics) == [ETANERCEPT_SYRINGE]


def test_the_charts_carry_medications_in_the_system_the_sets_declare(patients):
    """RxNorm, which is the reason a set of the LCD's own ICD-10 codes would
    have matched nobody (D52, REQ-59, D111)."""
    for patient_id in (RA1, RA2, RA3):
        systems = {
            m.system for m in patients.get_medications(patient_id) if m.system
        }
        assert systems == {RXNORM}, f"{patient_id[:12]}: {systems}"


def test_no_unreadable_order_hides_a_drug_a_criterion_reads(patients, population):
    """`get_medications` reads `medicationCodeableConcept` and does not follow a
    `medicationReference` (D111's stated scope). These charts carry such orders
    — measured for D113, all contraceptives and all completed — and this pins
    that none of them is methotrexate or an excluded biologic. If one ever is,
    RA3's abstention becomes an artifact of the adapter rather than a fact
    about the chart, and nothing else in the suite would notice."""
    for patient_id in (RA1, RA2, RA3):
        bundle = json.loads(
            (
                REPO_ROOT / "data" / "patients" / "bundles" /
                population[patient_id]["filename"]
            ).read_text(encoding="utf-8")
        )
        by_url = {e["fullUrl"]: e["resource"] for e in bundle["entry"] if "fullUrl" in e}
        hidden = []
        for entry in bundle["entry"]:
            resource = entry["resource"]
            if resource.get("resourceType") != "MedicationRequest":
                continue
            reference = (resource.get("medicationReference") or {}).get("reference")
            if not reference:
                continue
            medication = by_url.get(reference, {})
            hidden += [
                c.get("code")
                for c in medication.get("code", {}).get("coding", [])
            ]
        assert not ({METHOTREXATE_TABLET, ETANERCEPT_SYRINGE} & set(hidden)), (
            f"{patient_id[:12]}: a drug a criterion reads sits behind a "
            f"medicationReference the adapter does not follow: {hidden}"
        )


# --------------------------------------------------------------------------
# The verdicts the rows label
# --------------------------------------------------------------------------


def test_ra1_meets_both_claimed_criteria_and_abstains_on_the_rest(patients, policies):
    determination = _determine(patients, policies, RA1)
    assert determination.policy_version_id == TREE_ID
    assert determination.outcome is DeterminationOutcome.INSUFFICIENT_EVIDENCE
    verdicts = {r.criterion_id: r.verdict for r in determination.criterion_results}
    assert verdicts == {
        "a": CriterionVerdict.MET,
        "b": CriterionVerdict.MET,
        "c": CriterionVerdict.INSUFFICIENT_EVIDENCE,
        "d": CriterionVerdict.INSUFFICIENT_EVIDENCE,
        "e": CriterionVerdict.INSUFFICIENT_EVIDENCE,
    }
    reasons = {
        r.criterion_id: r.gap_reason
        for r in determination.criterion_results
        if r.gap_reason is not None
    }
    assert reasons == {
        "c": GapReason.NOT_EVALUATED_BY_THIS_SYSTEM,
        "d": GapReason.NOT_EVALUATED_BY_THIS_SYSTEM,
        "e": GapReason.NOT_EVALUATED_BY_THIS_SYSTEM,
    }, "the overall INSUFFICIENT_EVIDENCE is the unclaimed criteria's alone"


def test_ra3_abstains_on_the_drug_and_never_answers_not_met(patients, policies):
    determination = _determine(patients, policies, RA3)
    by_id = {r.criterion_id: r for r in determination.criterion_results}
    assert by_id["a"].verdict is CriterionVerdict.MET
    assert by_id["b"].verdict is CriterionVerdict.INSUFFICIENT_EVIDENCE
    assert by_id["b"].gap_reason is GapReason.NO_EVIDENCE_RETRIEVED
    assert not by_id["b"].spans, "an abstention cites nothing (Art. IV)"
    assert CriterionVerdict.NOT_MET not in {
        r.verdict for r in determination.criterion_results
    }, (
        "a chart with no prescription has not recorded that the patient is not "
        "taking the drug (D40's asymmetry, D111)"
    )


def test_ra2_is_not_covered_and_cites_the_prescription_that_fired_it(
    patients, policies, population
):
    determination = _determine(patients, policies, RA2)
    assert determination.outcome is DeterminationOutcome.NOT_COVERED
    assert determination.criterion_results == [], (
        "an exclusion answers before the criteria chain (D41)"
    )
    assert determination.exclusion_evidence, "a denial with no citation is Art. III skipped"
    quoted = "".join(
        patients.get_document(span.document_id).text[span.char_start : span.char_end]
        for span in determination.exclusion_evidence
    )
    assert ETANERCEPT_SYRINGE in quoted, (
        "the denial must cite the order that fired it, not some other resource "
        "on the chart"
    )
    assert METHOTREXATE_TABLET not in quoted, (
        "the limitation is about the drug infliximab is combined with; citing "
        "the methotrexate order would be citing the criterion it satisfies"
    )


def test_the_pair_differs_by_exactly_the_declared_prescription(patients, population):
    """RA1 and RA2 are one chart and one chart plus a prescription. Asserted
    over what the store reports, because that is what the criteria read."""
    source = {
        (m.code, m.status, m.authored_on) for m in patients.get_medications(RA1)
    }
    clone = {
        (m.code, m.status, m.authored_on) for m in patients.get_medications(RA2)
    }
    added = clone - source
    assert source - clone == set(), "the clone removes nothing"
    assert {code for code, _, _ in added} == {ETANERCEPT_SYRINGE}
    assert all(status == "active" for _, status, _ in added)


def test_every_rheumatology_determination_spends_no_model_call(patients, policies):
    for patient_id in (RA1, RA2, RA3):
        determination = _determine(patients, policies, patient_id)
        assert determination.model_calls == 0
        assert determination.metrics == []


def test_a_rheumatology_request_on_a_bariatric_chart_abstains(patients, policies):
    """The cross-practice case no row labels and the corpus supplies for free:
    a chart in Palmetto's territory with no rheumatology evidence on it at all.
    Every criterion abstains and none is `NOT_MET` — the system says it cannot
    tell, which is what an absent diagnosis licenses (D40) — and no verdict
    rests on anything the note pass produced.

    This chart carries notes, and that is how D113 found the cost the
    rheumatology rows cannot show: `step_extract` is an unconditional entry in
    `STEPS`, so a tree declaring no note criterion still pays to read every
    note on the chart. It changes no verdict, which is why it is a cost and
    not a defect, and it is `T-107`'s to remove — the row where the tree
    declares its extraction schema.
    """
    bariatric_chart_in_palmetto = "ee9d79ee-ba2e-5915-b6d5-c7e700066d40"
    determination = determine(
        policies,
        J_CODE,
        patient_id=bariatric_chart_in_palmetto,
        patient_store=patients,
        as_of=AS_OF,
        extraction_runner=_recorded_runner(),
        verifier=AcceptAllVerifier(),
    )
    assert determination.policy_version_id == TREE_ID
    assert determination.outcome is DeterminationOutcome.INSUFFICIENT_EVIDENCE
    assert {r.verdict for r in determination.criterion_results} == {
        CriterionVerdict.INSUFFICIENT_EVIDENCE
    }
    assert not any(r.spans for r in determination.criterion_results), (
        "no rheumatology criterion may cite this chart's weight-management "
        "notes: the practice boundary is the tree's, and an extracted event "
        "this tree declares no criterion for must reach no verdict"
    )


# --------------------------------------------------------------------------
# The rows and the charts describe the same thing
# --------------------------------------------------------------------------


def test_every_rheumatology_row_names_a_chart_in_the_cohort(cases, population):
    rows = {cid: c for cid, c in cases.items() if cid.startswith("RA")}
    assert set(rows) == {"RA1", "RA2", "RA3"}
    for case_id, case in rows.items():
        assert case["procedure_code"] == J_CODE
        assert population[case["patient_id"]]["cohort"] == "rheumatology"
        assert case["expect"]["policy_version_id"] == TREE_ID, (
            f"{case_id}: a row in a second practice pins which tree answered "
            "(D102's rule, D113)"
        )
        cited = sum(
            1
            for expected in (case["expect"].get("criteria") or {}).values()
            if expected["verdict"] in ("MET", "NOT_MET")
        )
        assert case["expect"]["max_model_calls"] == cited, (
            f"{case_id}: the budget is Article V's — one replayed verifier "
            "call per cited verdict and no extraction call, because this tree "
            "declares no note criterion. A budget above that would hide an "
            "extraction this practice has no use for"
        )
        assert "state" not in case, (
            f"{case_id}: the state is read from the bundle, as J1's is"
        )
